#!/usr/bin/env python3
"""Generate the Flatpak `python3-deps.yaml` module (offline, pinned wheels).

Flathub builds run offline, so every Python dependency must be listed as a
`file` source with a sha256. This script:

  1. resolves the full dependency closure of requirements.txt with pip (getting
     exact versions), then
  2. asks the PyPI JSON API for each package==version's wheel that matches the
     *target runtime's* Python tag (default cp313 for org.kde.Platform 6.11, which
     is built on freedesktop-sdk 25.08 / CPython 3.13), preferring an abi3 or
     pure-python wheel when there is no version-specific one, and
  3. writes a flatpak-builder module that pip-installs them with `--no-index`.

Re-run this whenever requirements change, or when bumping the runtime (change
--pytag to match the new runtime's CPython). Verify the result with a real
`flatpak-builder` run before submitting to Flathub — the tag assumption here
can't be validated without the SDK installed.

Usage:  python3 packaging/gen-python-deps.py [--pytag cp312] [--out packaging/python3-deps.yaml]
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def resolve_versions(reqfile: Path) -> dict[str, str]:
    """pip-download the closure to learn exact (package -> version)."""
    with tempfile.TemporaryDirectory() as td:
        subprocess.run(
            [sys.executable, "-m", "pip", "download", "-r", str(reqfile),
             "--only-binary=:all:", "-d", td],
            check=True, stdout=subprocess.DEVNULL)
        versions = {}
        for whl in Path(td).glob("*.whl"):
            name, ver = whl.name.split("-")[0], whl.name.split("-")[1]
            versions[name.replace("_", "-").lower()] = ver
        return versions


def pick_wheel(pkg: str, version: str, pytag: str) -> tuple[str, str, str]:
    """Return (filename, url, sha256) of the best wheel for `pytag`."""
    url = f"https://pypi.org/pypi/{pkg}/{version}/json"
    with urllib.request.urlopen(url, timeout=30) as r:
        data = json.load(r)
    wheels = [f for f in data["urls"] if f["packagetype"] == "bdist_wheel"]

    def rank(f):
        fn = f["filename"]
        # prefer: exact cpXY  >  abi3  >  pure py3  >  py2.py3 ; linux over any
        tagscore = (4 if pytag in fn else 3 if "abi3" in fn else
                    2 if "-py3-" in fn else 1 if "py2.py3" in fn else 0)
        archscore = 1 if ("manylinux" in fn or "linux_x86_64" in fn) else 0
        # exclude wheels for other arches / musl
        bad = any(x in fn for x in ("win_", "macosx", "musllinux", "aarch64",
                                    "i686", "ppc64", "s390x", "armv7"))
        return (-1, 0) if bad else (tagscore, archscore)

    best = max(wheels, key=rank, default=None)
    if best is None or rank(best)[0] <= 0:
        raise SystemExit(f"no suitable wheel for {pkg}=={version} (tag {pytag})")
    return best["filename"], best["url"], best["digests"]["sha256"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pytag", default="cp313",
                    help="CPython tag of the target runtime (KDE 6.11 -> cp313)")
    ap.add_argument("--out", default=str(ROOT / "packaging" / "python3-deps.yaml"))
    ap.add_argument("--reqs", default=str(ROOT / "requirements.txt"))
    args = ap.parse_args()

    versions = resolve_versions(Path(args.reqs))
    print(f"resolved {len(versions)} packages:", ", ".join(sorted(versions)))

    sources, install = [], []
    for pkg in sorted(versions):
        ver = versions[pkg]
        fn, url, sha = pick_wheel(pkg, ver, args.pytag)
        sources.append({"type": "file", "url": url, "sha256": sha})
        install.append(fn)
        print(f"  {pkg:20} {ver:12} -> {fn}")

    lines = [
        "# GENERATED by packaging/gen-python-deps.py — do not edit by hand.",
        f"# Wheels pinned for Python tag: {args.pytag} (match to the runtime).",
        "name: python3-deps",
        "buildsystem: simple",
        "build-commands:",
        "  - pip3 install --no-index --find-links=\"file://${PWD}\""
        " --prefix=${FLATPAK_DEST} --no-build-isolation " + " ".join(install),
        "sources:",
    ]
    for s in sources:
        lines.append("  - type: file")
        lines.append(f"    url: {s['url']}")
        lines.append(f"    sha256: {s['sha256']}")

    Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"\nwrote {args.out}  ({len(sources)} wheels)")


if __name__ == "__main__":
    main()
